import { createClient } from '@supabase/supabase-js'

export const supabaseUrl = "https://llzgsfjqysctspbdnben.supabase.co"

export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsemdzZmpxeXNjdHNwYmRuYmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg3NTQ5NjEsImV4cCI6MTk4NDMzMDk2MX0.U01tYXo0nbjoJk8FspiSLoXmgvfAm1RT3TYbN_b1Tpg"

export const supabaseService_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsemdzZmpxeXNjdHNwYmRuYmVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY2ODc1NDk2MSwiZXhwIjoxOTg0MzMwOTYxfQ._FztjxwpdKER20MGPHhSBH1QBZaGxa4RsV7AYTOYdOU"

export const supabase = createClient(supabaseUrl, supabaseAnonKey)